### ISSUE TITLE
Custom Error Message

### ISSUE THREAD

**Issue by hannadrehman** [balavishnuvj/react-hooks-form-validator#8]
i wanted to add a custom error message for my `required` form field. but readme did not show anyway of adding it. 
but then i checked code and field validator was taking it. pls update the readme with all fields properties 
thanks :) 

```
required: [
    { type: 'boolean', optional: true },
    {
      type: 'object',
      optional: true,
      props: {
        errorMsg: { type: 'string' },
      },
    },
  ]

```

**Comment by ali412** [comment]
Hello guys.
I have this problem too.
please help us to solve this solution.

Thanks guys

**Comment by balavishnuvj** [comment]
@hannadrehman @alikhancherli  this feature was included in the library. Missed to document.

you can do 
```js
{
  fieldName: {
    required: {
      errorMsg: 'Custom required error message';
    }
  }
}
```
